### PR TITLE
Backend CORS

### LINKED ISSUE #51: Add CORS to Flask app
Since the client is going to be hosted on a different port at minimum and a different domain potentially, our server needs to allow for cross-origin resource sharing (CORS). We should also potentially look into how to tighten the security with CORS since by default the security is relatively lax.

### PR DESCRIPTION
**Pull request by JimothyGreene**
### Problem
The server didn't enable Cross-Origin Resource Sharing, so requests coming from other domains were not allowed. This would have led to our client being unable to make requests to our server (quite a big issue).

### Solution
Using the `flask-cors` module, we can simply create a `CORS` object and initialize it with our flask app. This easily enables CORS on our API.

### Testing
Using the SwaggerUI web interface, there is an option to send a request in the format specified by our YAML files. Before adding CORS, this request was denied because the SwaggerUI server was hosted on a different domain (port 8080) than our API (port 5000). After adding CORS, I was able to successfully send a login request to the server.

### Notes
This does open our API up to _all_ domains, so we may want to look into how to restrict that when the time comes to deploy. I'm not entirely sure how the small details of CORS works, so that'll require some research. Also, it looks like we can now use SwaggerUI to test our routes (which will also force us to document along the way) instead of Postman. But we can use both also.

Closes #51

### CODE REVIEW

**Review by ishan0102 — APPROVED** [review]
Lgtm

**Comment by maxwithrow** [comment]
I know this isn't really a part of this PR/Task, but since this PR is super short and this fix would be real quick too, do you think you could go ahead and have `users/register` return a jwt? Just so we don't have to make 2 separate API calls to get the token

**Comment by JimothyGreene** [comment]
> I know this isn't really a part of this PR/Task, but since this PR is super short and this fix would be real quick too, do you think you could go ahead and have `users/register` return a jwt? Just so we don't have to make 2 separate API calls to get the token

Yeah for sure. I'll probably open a new PR just to keep it all separated, but I can fix that real quick.

**Comment by maxwithrow** [comment]
> > I know this isn't really a part of this PR/Task, but since this PR is super short and this fix would be real quick too, do you think you could go ahead and have `users/register` return a jwt? Just so we don't have to make 2 separate API calls to get the token
> 
> Yeah for sure. I'll probably open a new PR just to keep it all separated, but I can fix that real quick.

Perfect, I'll just go ahead and give you an approval since this is real straight forward and lgtm

**Review by maxwithrow — APPROVED** [review]

**Pull request merged**
