### PR TITLE
Updates Projects documentation

### LINKED ISSUE #104: Fix Project Swagger
Projects swagger is incorrect after #102. This needs to be updated

### PR DESCRIPTION
**Pull request by JimothyGreene**
### Problem
The projects swagger documentation was incorrect with the new project ID request type. This was causing issues with communication with frontend.

### Solution
Update the Swagger documentation to reflect the new changes so that all the information is well-documented.

### Testing
I tested this by loading up Swagger and checking that the format was correct.

Closes #104

### CODE REVIEW

**Review by mxchen2001 — COMMENTED** [review]
Look good but in `project_w_id.yml` the summary for GET should be changed from "updated" "read" and in `project_w_oid.yml` the operationId for DELETE should be changed from "updateProject" to "deleteProject"

**Comment by JimothyGreene** [comment]
> Look good but in `project_w_id.yml` the summary for GET should be changed from "updated" "read" and in `project_w_oid.yml` the operationId for DELETE should be changed from "updateProject" to "deleteProject"

Fixed

**Review by ishan0102 — APPROVED** [review]
Lgtm

**Review by mxchen2001 — APPROVED** [review]
lgtm

**Pull request merged**
